# Solving a System of Linear Equations Using Matrix Inversion

This method to solve linear algebra equations only works if:
1. The matrix is SQUARE.
2. The matrix isn't singular - This means that one row of the matrix is a multiple of another row in the matrix, which implies that the 2 lines are parallel - so there will never be an intersection.

Example of a singular matrix:
$$
\begin{bmatrix}
-4 & 1 \\
-8 & 2
\end{bmatrix}
$$


We are given the following system of linear equations:

\begin{cases}
4b + 2c = 4 \\
-5b - 3c = -7
\end{cases}

This can be represented in matrix form as:

$$ A \cdot \mathbf{x} = \mathbf{y} $$

The solution is given by:

$$ \mathbf{x} = A^{-1} \cdot \mathbf{y} $$

In [1]:
import torch

In [9]:
X = torch.tensor([[4,2], [-5, -3.]]) #A matrix
y = torch.tensor([[4], [-7.]])
inverseX = torch.inverse(X)
bc = torch.matmul(inverseX, y)
print(bc)

tensor([[-1.],
        [ 4.]])


**A vector multiplied by an indentity matrix will always equal itself.**

In [12]:
X = torch.tensor([[2, 4, 6, 7.]]) #A matrix
Identity = torch.eye(4)
XI = torch.matmul(X, Identity)
print(XI == X)

tensor([[True, True, True, True]])


**The inverse of an identity matrix is always equals itself.**

$$
I^{-1} = I
$$

In [19]:
I = torch.eye(3)
inverseI = torch.inverse(I)
print(I == inverseI)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# Diagonal Matrices

A **diagonal matrix** is a square matrix in which the entries outside the main diagonal are all zero. The main diagonal can have any values.

### General Form
A diagonal matrix \( D \) of size \( n \times n \) looks like this:

$$
D =
\begin{bmatrix}
d_1 & 0 & 0 & \cdots & 0 \\
0 & d_2 & 0 & \cdots & 0 \\
0 & 0 & d_3 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & d_n
\end{bmatrix}
$$

Where \( d_1, d_2, \dots, d_n \) are the diagonal elements, and all off-diagonal elements are zero.

### Properties of Diagonal Matrices

1. **Addition**: The sum of two diagonal matrices is also a diagonal matrix. 
   If \( D_1 \) and \( D_2 \) are diagonal matrices, then:
   $$
   D_1 + D_2 =
   \begin{bmatrix}
   d_{11} + d_{12} & 0 & 0 & \cdots & 0 \\
   0 & d_{22} + d_{22} & 0 & \cdots & 0 \\
   0 & 0 & d_{33} + d_{33} & \cdots & 0 \\
   \vdots & \vdots & \vdots & \ddots & \vdots \\
   0 & 0 & 0 & \cdots & d_{nn} + d_{nn}
   \end{bmatrix}
   $$

2. **Multiplication**: The product of two diagonal matrices is also a diagonal matrix, where each diagonal element is the product of the corresponding diagonal elements of the original matrices.
   $$ 
   D_1 \times D_2 =
   \begin{bmatrix}
   d_{11} \cdot d_{12} & 0 & 0 & \cdots & 0 \\
   0 & d_{22} \cdot d_{22} & 0 & \cdots & 0 \\
   0 & 0 & d_{33} \cdot d_{33} & \cdots & 0 \\
   \vdots & \vdots & \vdots & \ddots & \vdots \\
   0 & 0 & 0 & \cdots & d_{nn} \cdot d_{nn}
   \end{bmatrix}
   $$

3. **Inverse**: The inverse of a diagonal matrix \( D \) exists as long as none of the diagonal elements are zero. If \( D \) is invertible, its inverse \( D^{-1} \) is also a diagonal matrix with reciprocal values on the diagonal.
   $$ 
   D^{-1} =
   \begin{bmatrix}
   \frac{1}{d_1} & 0 & 0 & \cdots & 0 \\
   0 & \frac{1}{d_2} & 0 & \cdots & 0 \\
   0 & 0 & \frac{1}{d_3} & \cdots & 0 \\
   \vdots & \vdots & \vdots & \ddots & \vdots \\
   0 & 0 & 0 & \cdots & \frac{1}{d_n}
   \end{bmatrix}
   $$

4. **Eigenvalues**: The diagonal elements of a diagonal matrix are the eigenvalues of that matrix.

### Example

Consider the following diagonal matrix:

$$
D =
\begin{bmatrix}
3 & 0 & 0 \\
0 & 5 & 0 \\
0 & 0 & 7
\end{bmatrix}
$$

This matrix has eigenvalues \( 3, 5, 7 \), and if you multiply \( D \) by a scalar, the result is another diagonal matrix where each diagonal element is multiplied by that scalar.

### Applications

- Diagonal matrices are used in **diagonalization** of matrices.
- They simplify matrix operations, such as finding powers or determinants.
- They appear in many areas of physics and engineering, such as systems of equations and transformations.


In [25]:
#Showing the inverse of a diagonal matrix
diagonal = torch.tensor([1, 10, 100.])
D = torch.diag(diagonal)
inverseD = torch.inverse(D)
print(inverseD)

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 0.1000, 0.0000],
        [0.0000, 0.0000, 0.0100]])
